name: Publish to NPM & GitHub Packages

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write # Required for OIDC
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm publish

      - run: npm publish --registry=https://npm.pkg.github.com
